### ISSUE TITLE
About ConformerTransfucer structure

### ISSUE THREAD

**Issue by alsm168** [Z-yq/TensorflowASR#2]
Hello，I have another question. In your code ConformerTransfucer‘s TransducerPrediction is implemented with LSTM， CanTransducerPrediction be implemented with Conformer block? thank you

**Comment by Z-yq** [comment]
Maybe you wanne CTC structure.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Z-yq/TensorflowASR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 下午4:25
收件人:&nbsp;"Z-yq/TensorflowASR"<TensorflowASR@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Z-yq/TensorflowASR] About ConformerTransfucer structure (#2)





 
Hello，I have another question. In your code ConformerTransfucer‘s TransducerPrediction is implemented with LSTM， CanTransducerPrediction be implemented with Conformer block? thank you

**Comment by alsm168** [comment]
Thank you. I just read the paper of Conformer ,TransducerPrediction is implemented with LSTM. I think it can also be implemented with transformer.

**Comment by Z-yq** [comment]
That's a good idea, you can try it.



But it's hard for online streaming.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Z-yq/TensorflowASR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 下午4:45
收件人:&nbsp;"Z-yq/TensorflowASR"<TensorflowASR@noreply.github.com&gt;;
抄送:&nbsp;"　Ｄｅｍｏｎ丶"<641242921@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Z-yq/TensorflowASR] About ConformerTransfucer structure (#2)





 
Thank you. I just read the paper of Conformer ,TransducerPrediction is implemented with LSTM. I think it can also be implemented with transformer.

**Comment by alsm168** [comment]
thanks，I learned a lot from your code.  It is great!
