### ISSUE TITLE
语言模型训练太慢

### ISSUE THREAD

**Issue by zhaoyukoon** [Z-yq/TensorflowASR#24]
我计划基于 `TensorflowASR` 训练一个语言模型。使用的数据规模在1000万句。使用默认的 `train_lm.py`，且按照说明把 BERT 模型也下载了下来。

按照目前的速度，一个 epoch要的时间要上百天。
我使用的是 3090Ti 单卡。

**Comment by Z-yq** [comment]
已优化数据加载
