### ISSUE TITLE
关于Conformer模型中使用的位置编码的一些疑惑

### ISSUE THREAD

**Issue by mlxu995** [Z-yq/TensorflowASR#3]
这是一个很棒的项目。据我所知，你是第一个用tensorflow将目前最先进的ASR模型整合实现的人。
在我读到Conformer模型的实现时产生了两个疑惑。第一个疑惑是你在Conformer中的每一个block都加入了位置编码，这与我在其他地方了解到的实现有点不一样。这样做会降低模型的错误率吗？
另外是你只使用了Conformer中的卷积结构，而没有使用相对位置编码，这样做会对模型产生什么影响？

**Comment by Z-yq** [comment]
感谢认可：）




1.个人的一些经验，位置编码对MHA这种结构的作用更加明显，所以在MHA层中加了位置编码。
2.理由基本和（1）一致，CNN或者RNNs结构对位置编码不敏感。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Z-yq/TensorflowASR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月1日(星期四) 晚上11:03
收件人:&nbsp;"Z-yq/TensorflowASR"<TensorflowASR@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Z-yq/TensorflowASR] 关于Conformer模型中使用的位置编码的一些疑惑 (#3)





 
这是一个很棒的项目。据我所知，你是第一个用tensorflow将目前最先进的ASR模型整合实现的人。
 在我读到Conformer模型的实现时产生了两个疑惑。第一个疑惑是你在Conformer中的每一个block都加入了位置编码，这与我在其他地方了解到的实现有点不一样。这样做会降低模型的错误率吗？
 另外是你只使用了Conformer中的卷积结构，而没有使用相对位置编码，这样做会对模型产生什么影响？

**Comment by Z-yq** [comment]
很久没有更新，关闭该issue
