### ISSUE TITLE
训练am模型的时候，内存一直下降。下降到几百兆

### ISSUE THREAD

**Issue by freefly518** [Z-yq/TensorflowASR#30]
训练am模型
数据是aishell 1
am_data.yml
conformerS.yml

有遇到过这个问题的吗？

**Comment by Z-yq** [comment]
这个不影响训练的话就不用管吧

**Comment by freefly518** [comment]
消耗内存太多100G 都没了。你训练的时候用的几个GPU 多大内存。我试了一下你训练好的模型，效果还不错的。
