### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed 

### ISSUE THREAD

**Issue by kenzoukun** [Z-yq/TensorflowASR#34]
tensorflow==2.2.0
tensorflow-addons==0.10.0
keras-bert>=0.81.0
--------------------------------
The above are some installation package versions，when I run "python train_am.py", error "tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed " happended.
 Thanks for your help.

**Comment by Z-yq** [comment]
Maybe your GPU is occupied
