### ISSUE TITLE
数字好像无法识别，这个应该如何优化处理？

### ISSUE THREAD

**Issue by laoyin** [Z-yq/TensorflowASR#35]
比如：语音2020你那12月12号，识别出结果： "年。月。号。/S"

**Comment by ChristopheZhao** [comment]
你有没有对标签进行处理?pypinyin默认是不能把数字转成pinyin的,需要你自己先把数字转成汉字,用pypinyin才能转成拼音.

**Comment by laoyin** [comment]
@ZhaoJiangJie 好的，感谢，我们现在也是这么改的
