### ISSUE TITLE
Fix pacakges name in requirements.txt

### ISSUE THREAD

**Issue by phecda-xu** [Z-yq/TensorflowASR#4]
hi:

Getting error when use `pip install -r requirements.txt`.

It should be `keras-bert`  and `tensorflow-addons`.

**Comment by Z-yq** [comment]
感谢指出bug，：）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Z-yq/TensorflowASR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月4日(星期天) 下午2:57
收件人:&nbsp;"Z-yq/TensorflowASR"<TensorflowASR@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Z-yq/TensorflowASR] Fix pacakges name in requirements.txt (#4)





 
hi:
 
Getting error when use pip install -r requirements.txt.
 
It should be keras-bert  and tensorflow-addons.
