### ISSUE TITLE
关于使用Tester 来大批量测试

### ISSUE THREAD

**Issue by oneappleya** [Z-yq/TensorflowASR#42]
请问可以直接下载您训练好的模型，如ConformerCTC(S)，用来测试吗？
我使用您训练好的ConformerCTC(S)，在准备好的test_list下，当运行python eval_am.py --data_config ./asr/configs/am_data.yml --model_config ./asr/configs/ConformerS.yml 的时候会出现一下错误：
outputs = call_fn(inputs, *args, **kwargs)
TypeError: call() got multiple values for argument 'training'
想请问一下这怎么解决

**Comment by Z-yq** [comment]
可能有bug。。。。我看一下

**Comment by Z-yq** [comment]
./asr/tester/am_tester.py  line:41  
  translator_out = self.translator(ctc_decode, enc_output, training=False)
====>>>>
  translator_out = self.translator([ctc_decode, enc_output], training=False)

**Comment by oneappleya** [comment]
感谢感谢
