### ISSUE TITLE
关于train_loss、ctc_loss和translate_loss的关系有些疑问

### ISSUE THREAD

**Issue by JunZhan2000** [Z-yq/TensorflowASR#46]
您好，我在代码中看了一下loss的计算。
我的理解是ctc_loss是encoder+decoder的loss，translate_loss是translator的loss，train_loss=ctc_loss+translate_loss*2，最后用train_loss对整个模型进行端到端的训练，是这样吗
但是我看训练过程打印出来的loss不符合这个规律，比如某时刻是train_loss=210.327, ctc_loss=3.709, translate_loss=1.432，是我的理解有什么问题吗，希望可以得到解答，谢谢！

**Comment by Z-yq** [comment]
实际loss在 210.327/32 ， 210.327 是metric 将batch loss求和显示了

**Comment by JunZhan2000** [comment]
原来如此，多谢指教！
