### ISSUE TITLE
关于标点恢复模型OOV的问问

### ISSUE THREAD

**Issue by uloveqian2021** [Z-yq/TensorflowASR#47]
您好，我在使用标点恢复模型时，发现存在未登录词的情况，我看词表里没有“unk” 这样的字符， 对于不存在字表里的中文字会报错

**Comment by Z-yq** [comment]
可以将没有的词先剔除掉，得到标点结果后，再插入

**Comment by uloveqian2021** [comment]
> 可以将没有的词先剔除掉，得到标点结果后，再插入

好的，谢谢，方便问一下大佬用的是哪一个数据集训练的模型吗

**Comment by Z-yq** [comment]
NLP 的开源数据集
