### ISSUE TITLE
No reference in the code

### ISSUE THREAD

**Issue by nglehuy** [Z-yq/TensorflowASR#6]
Did you copy the code from my repository [https://github.com/usimarit/TiramisuASR](https://github.com/usimarit/TiramisuASR)?
I looked into the code and I see it look like the code I wrote.
It would be nice if you could write references to where you learn and take source code or any kind of knowledge involving in this repo. Other authors would appreciate it.

**Comment by Z-yq** [comment]
Sorry, I didn't add reference in time.
Because the code is still in the development stage, and there will be additions, deletions, etc.
The expectation is to add relevant references after debugging and functional verification. 
I will add reference in soon.

**Comment by nglehuy** [comment]
Alright, I just want to remind you about this :smiley:
