### ISSUE TITLE
Is there any model that can support tflite conversion?

### ISSUE THREAD

**Issue by mapledxf** [Z-yq/TensorflowASR#7]
I have noticed that `enable_tflite_convertible:` is commented as `not support true' in all models' config.
Any plan to implement this function?

**Comment by Z-yq** [comment]
I tried to convert RNNT and LAS structures to TFLITE before, but unfortunately both failed.So the current plan is to validate functionality, provide relevant pre-training models and performance results, and finally tackle TFLITE.
By the way, I can only study this problem in my spare time, so I may not have any results until the end of the year.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Z-yq/TensorflowASR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 下午3:45
收件人:&nbsp;"Z-yq/TensorflowASR"<TensorflowASR@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Z-yq/TensorflowASR] Is there any model that can support tflite conversion? (#7)





 
I have noticed that enable_tflite_convertible: is commented as `not support true' in all models' config.
 Any plan to implement this function?
