### ISSUE TITLE
mask of multiheadattention in conformer ？

### ISSUE THREAD

**Issue by alsm168** [Z-yq/TensorflowASR#8]
Hi
  I see the multiheadattention in conformer needs mask, Is there the code to generate the mask? thank you

**Comment by Z-yq** [comment]
I think that in the acoustic model, the role of mask is not particularly obvious, so there is no mask added. If you really need a mask, you can follow the method in transformer.
locate in:

LMmodel/tf2_trm.py


create_masks()&nbsp; #from tensorflow offical guide



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Z-yq/TensorflowASR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 下午2:53
收件人:&nbsp;"Z-yq/TensorflowASR"<TensorflowASR@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Z-yq/TensorflowASR] mask of multiheadattention in conformer ？ (#8)





 
Hi
 I see the multiheadattention in conformer needs mask, Is there the code to generate the mask? thank you

**Comment by alsm168** [comment]
ok，I'll try it later,thanks
