### ISSUE TITLE
是否支持分布式训练

### ISSUE THREAD

**Issue by wangguangyuan** [Z-yq/TensorflowASR#9]
感谢开源这么好的工作，请教一下是否支持单机多卡和多机多卡训练？

**Comment by Z-yq** [comment]
现在支持单机多卡的训练。如果要使用多机多卡，需要为runner提供相应的strategy。
可遵循tensorflow官网的教程进行配置。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Z-yq/TensorflowASR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月20日(星期二) 上午9:12
收件人:&nbsp;"Z-yq/TensorflowASR"<TensorflowASR@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Z-yq/TensorflowASR] 是否支持分布式训练 (#9)





 
感谢开源这么好的工作，请教一下是否支持单机多卡和多机多卡训练？
